### PR TITLE
Boom! An update to support NPM, plus a handy jQuery plugin;

### PR DESCRIPTION
**Pull request by seangates**
Eddie,

First, thanks for the great work to get this going. I've actually been looking at this project off and on for about 3 years (yes, that long!).

Secondly, I want to make sure you understand what I'm trying to do with this pull request: make the library more accessible to others.

So, what I'm proposing with this pull request is an update in order to prepare the code for use in NPM (http://npmjs.org) which will increase its visibility, and allow people to use it in their JavaScript projects much more easily. NPM is heavily used and this package will gain some fantastic momentum once published there. (We can discuss the "how" of submitting the package.)

Lastly, I created a jQuery plugin for the simple fact that people love jQuery and use it almost everywhere.

So, without further ado I present ... BarcodeReader.

Thanks!
— Sean

(P.S.: Please contact me ASAP since I want to get this into NPM sooner rather than later.)

### CODE REVIEW

**Comment by EddieLa** [comment]
Hi,

Awesome work I'm glad to see there's still some interest about this, I looked through it and there doesn't seem to be any problems so I'll merge it right away.

I'll keep an eye out if you want to discuss the "how" of submitting the package.

Thanks,
Eddie

**Comment by seangates** [comment]
Eddie,

Thanks for merging it! Here are the simple steps to publish the NPM package: https://docs.npmjs.com/getting-started/publishing-npm-packages

Let me know if you need any help!

— Sean

**Comment by seangates** [comment]
Oh, and I called the package "barcode-reader", since there are no uppercase letters in NPM package names.

**Comment by seangates** [comment]
Or, I can publish the package for you, I guess.

**Comment by seangates** [comment]
I'm publishing. I needed it today. :smile: 

So, please sign up at npmjs.org and I can make you an owner of the package. https://www.npmjs.com/signup

**Comment by EddieLa** [comment]
Alright no problem, https://www.npmjs.com/~eddiela

**Comment by seangates** [comment]
You were added, no problem. :+1: Now you can publish it, too.

**Pull request merged**
